
ignore_label: -100
# viz on point cloud? use points from PTH data
viz_pc: true
viz_mesh: false

# use sampled_ or vtx_ properties?
use_sampled: true

# viz on mesh? load mesh separately
data_root: /mnt/hdd/scannetpp/data

viz_semantic: true
viz_instances: true

scene_list: /mnt/hdd/scannetpp/splits/nvs_sem_train.txt
pth_dir: /mnt/hdd/scannetpp/sampled_data
out_dir: /mnt/hdd/scannetpp/viz

output_suffix:
  semantic: _gt_sem 
  instance: _gt_inst

palette_path: /home/stellwag/datasets/scannetpp/toolkit/semantic/configs/palette.txt
